<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DSRulesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $ds_rules=[
        	['id_penyakit'=>'P1', 'id_gejala'=>'G4', 'bobot'=>'0.5'],
        	['id_penyakit'=>'P1', 'id_gejala'=>'G6', 'bobot'=>'0.5'],
        	['id_penyakit'=>'P1', 'id_gejala'=>'G7', 'bobot'=>'0.3'],
        	['id_penyakit'=>'P1', 'id_gejala'=>'G11', 'bobot'=>'0.6'],
        	['id_penyakit'=>'P1', 'id_gejala'=>'G19', 'bobot'=>'0.6'],
        	['id_penyakit'=>'P1', 'id_gejala'=>'G20', 'bobot'=>'0.5'],
        	['id_penyakit'=>'P1', 'id_gejala'=>'G33', 'bobot'=>'0.8'],
        	['id_penyakit'=>'P1', 'id_gejala'=>'G34', 'bobot'=>'1'],
        	['id_penyakit'=>'P1', 'id_gejala'=>'G36', 'bobot'=>'0.2'],
        	['id_penyakit'=>'P1', 'id_gejala'=>'G38', 'bobot'=>'0.7'],
        	['id_penyakit'=>'P2', 'id_gejala'=>'G7', 'bobot'=>'0.5'],
        	['id_penyakit'=>'P2', 'id_gejala'=>'G9', 'bobot'=>'0.4'],
        	['id_penyakit'=>'P2', 'id_gejala'=>'G10', 'bobot'=>'0.3'],
        	['id_penyakit'=>'P2', 'id_gejala'=>'G15', 'bobot'=>'0.6'],
        	['id_penyakit'=>'P2', 'id_gejala'=>'G18', 'bobot'=>'0.3'],
        	['id_penyakit'=>'P2', 'id_gejala'=>'G19', 'bobot'=>'0.4'],
        	['id_penyakit'=>'P2', 'id_gejala'=>'G20', 'bobot'=>'0.4'],
        	['id_penyakit'=>'P2', 'id_gejala'=>'G28', 'bobot'=>'0.4'],
        	['id_penyakit'=>'P2', 'id_gejala'=>'G30', 'bobot'=>'0.4'],
        	['id_penyakit'=>'P2', 'id_gejala'=>'G31', 'bobot'=>'0.2'],
        	['id_penyakit'=>'P2', 'id_gejala'=>'G34', 'bobot'=>'0.7'],
        	['id_penyakit'=>'P2', 'id_gejala'=>'G38', 'bobot'=>'0.7'],
        	['id_penyakit'=>'P3', 'id_gejala'=>'G2', 'bobot'=>'0.5'],
        	['id_penyakit'=>'P3', 'id_gejala'=>'G5', 'bobot'=>'0.8'],
        	['id_penyakit'=>'P3', 'id_gejala'=>'G12', 'bobot'=>'0.8'],
        	['id_penyakit'=>'P3', 'id_gejala'=>'G13', 'bobot'=>'0.4'],
        	['id_penyakit'=>'P3', 'id_gejala'=>'G14', 'bobot'=>'0.8'],
        	['id_penyakit'=>'P3', 'id_gejala'=>'G24', 'bobot'=>'0.7'],
        	['id_penyakit'=>'P3', 'id_gejala'=>'G25', 'bobot'=>'0.7'],
        	['id_penyakit'=>'P3', 'id_gejala'=>'G41', 'bobot'=>'0.5'],
        	['id_penyakit'=>'P3', 'id_gejala'=>'G46', 'bobot'=>'0.5'],
        	['id_penyakit'=>'P4', 'id_gejala'=>'G3', 'bobot'=>'0.3'],
        	['id_penyakit'=>'P4', 'id_gejala'=>'G7', 'bobot'=>'0.4'],
        	['id_penyakit'=>'P4', 'id_gejala'=>'G15', 'bobot'=>'0.8'],
        	['id_penyakit'=>'P4', 'id_gejala'=>'G16', 'bobot'=>'0.8'],
        	['id_penyakit'=>'P4', 'id_gejala'=>'G27', 'bobot'=>'0.7'],
        	['id_penyakit'=>'P4', 'id_gejala'=>'G33', 'bobot'=>'0.8'],
        	['id_penyakit'=>'P4', 'id_gejala'=>'G35', 'bobot'=>'0.5'],
        	['id_penyakit'=>'P4', 'id_gejala'=>'G39', 'bobot'=>'0.5'],
        	['id_penyakit'=>'P4', 'id_gejala'=>'G40', 'bobot'=>'0.6'],
        	['id_penyakit'=>'P4', 'id_gejala'=>'G41', 'bobot'=>'0.7'],
        	['id_penyakit'=>'P5', 'id_gejala'=>'G5', 'bobot'=>'0.5'],
        	['id_penyakit'=>'P5', 'id_gejala'=>'G7', 'bobot'=>'0.5'],
        	['id_penyakit'=>'P5', 'id_gejala'=>'G12', 'bobot'=>'0.5'],
        	['id_penyakit'=>'P5', 'id_gejala'=>'G14', 'bobot'=>'0.6'],
        	['id_penyakit'=>'P5', 'id_gejala'=>'G15', 'bobot'=>'0.6'],
        	['id_penyakit'=>'P5', 'id_gejala'=>'G17', 'bobot'=>'0.8'],
        	['id_penyakit'=>'P5', 'id_gejala'=>'G26', 'bobot'=>'0.5'],
        	['id_penyakit'=>'P5', 'id_gejala'=>'G27', 'bobot'=>'0.7'],
        	['id_penyakit'=>'P5', 'id_gejala'=>'G33', 'bobot'=>'0.5'],
        	['id_penyakit'=>'P5', 'id_gejala'=>'G40', 'bobot'=>'0.4'],
        	['id_penyakit'=>'P5', 'id_gejala'=>'G41', 'bobot'=>'0.4'],
        	['id_penyakit'=>'P6', 'id_gejala'=>'G8', 'bobot'=>'0.7'],
        	['id_penyakit'=>'P6', 'id_gejala'=>'G15', 'bobot'=>'0.7'],
        	['id_penyakit'=>'P6', 'id_gejala'=>'G22', 'bobot'=>'0.4'],
        	['id_penyakit'=>'P6', 'id_gejala'=>'G29', 'bobot'=>'0.7'],
        	['id_penyakit'=>'P6', 'id_gejala'=>'G37', 'bobot'=>'0.6'],
        	['id_penyakit'=>'P6', 'id_gejala'=>'G39', 'bobot'=>'0.4'],
        	['id_penyakit'=>'P6', 'id_gejala'=>'G41', 'bobot'=>'0.8'],
        	['id_penyakit'=>'P6', 'id_gejala'=>'G47', 'bobot'=>'0.5'],
        	['id_penyakit'=>'P6', 'id_gejala'=>'G48', 'bobot'=>'0.5'],
        	['id_penyakit'=>'P7', 'id_gejala'=>'G2', 'bobot'=>'0.7'],
        	['id_penyakit'=>'P7', 'id_gejala'=>'G5', 'bobot'=>'0.4'],
        	['id_penyakit'=>'P7', 'id_gejala'=>'G7', 'bobot'=>'0.7'],
        	['id_penyakit'=>'P7', 'id_gejala'=>'G14', 'bobot'=>'0.6'],
        	['id_penyakit'=>'P7', 'id_gejala'=>'G21', 'bobot'=>'0.7'],
        	['id_penyakit'=>'P7', 'id_gejala'=>'G28', 'bobot'=>'0.7'],
        	['id_penyakit'=>'P7', 'id_gejala'=>'G30', 'bobot'=>'0.5'],
        	['id_penyakit'=>'P7', 'id_gejala'=>'G32', 'bobot'=>'0.6'],
        	['id_penyakit'=>'P7', 'id_gejala'=>'G44', 'bobot'=>'0.5'],
        	['id_penyakit'=>'P7', 'id_gejala'=>'G45', 'bobot'=>'0.5'],
        	['id_penyakit'=>'P8', 'id_gejala'=>'G1', 'bobot'=>'0.8'],
        	['id_penyakit'=>'P8', 'id_gejala'=>'G2', 'bobot'=>'0.6'],
        	['id_penyakit'=>'P8', 'id_gejala'=>'G3', 'bobot'=>'0.7'],
        	['id_penyakit'=>'P8', 'id_gejala'=>'G21', 'bobot'=>'0.7'],
        	['id_penyakit'=>'P8', 'id_gejala'=>'G22', 'bobot'=>'0.5'],
        	['id_penyakit'=>'P8', 'id_gejala'=>'G23', 'bobot'=>'0.5'],
        	['id_penyakit'=>'P8', 'id_gejala'=>'G28', 'bobot'=>'0.7'],
        	['id_penyakit'=>'P8', 'id_gejala'=>'G33', 'bobot'=>'0.5'],
        	['id_penyakit'=>'P8', 'id_gejala'=>'G36', 'bobot'=>'0.5'],
        	['id_penyakit'=>'P8', 'id_gejala'=>'G39', 'bobot'=>'0.9'],
        	['id_penyakit'=>'P8', 'id_gejala'=>'G42', 'bobot'=>'0.5'],
        	['id_penyakit'=>'P8', 'id_gejala'=>'G44', 'bobot'=>'0.5'],
        	['id_penyakit'=>'P9', 'id_gejala'=>'G2', 'bobot'=>'0.5'],
        	['id_penyakit'=>'P9', 'id_gejala'=>'G7', 'bobot'=>'0.5'],
        	['id_penyakit'=>'P9', 'id_gejala'=>'G33', 'bobot'=>'0.4'],
        	['id_penyakit'=>'P9', 'id_gejala'=>'G36', 'bobot'=>'0.4'],
        	['id_penyakit'=>'P9', 'id_gejala'=>'G39', 'bobot'=>'0.5'],
        	['id_penyakit'=>'P9', 'id_gejala'=>'G42', 'bobot'=>'0.7'],
        	['id_penyakit'=>'P9', 'id_gejala'=>'G43', 'bobot'=>'0.7'],
        	['id_penyakit'=>'P9', 'id_gejala'=>'G46', 'bobot'=>'0.6'],
        ];
        DB::table('ds_rules')->insert($ds_rules);
    }
}
